runtime: python27
threadsafe: true
api_version: 1

service: default

handlers:
- url: /main/static
  static_dir: static
- url: /main/.*
  script: main.app

env_variables:
  OAUTHLIB_INSECURE_TRANSPORT: 1

libraries:
- name: jinja2
  version: "latest"
- name: webapp2
  version: "latest"
- name: ssl
  version: "latest"
